### ISSUE TITLE
Legend Not Appear 

### ISSUE THREAD

**Issue by Mohamed-Abden** [FVANCOP/ChartNew.js#42] opened 2014-05-29 12:28 UTC
![screen shot 2014-05-29 at 2 26 30 pm](https://cloud.githubusercontent.com/assets/3175822/3117417/9955536a-e72c-11e3-9124-4f6cdf3cc207.png)
i build ChartData Dynamic
this is my ChartOptions : 

        $scope.myChartOptions =  {
            inGraphDataShow : true,
            datasetFill : false,
            scaleTickSizeRight : 0,
            scaleTickSizeLeft : 0,
            scaleTickSizeBottom :0,
            scaleTickSizeTop : 0,
            scaleFontSize : 20,
            canvasBorders : false,
            canvasBordersWidth :1,
            canvasBordersColor : "black",
            graphTitle : "Attendance",
            graphTitleFontFamily : "'Arial'",
            graphTitleFontSize : 24,
            graphTitleFontStyle : "bold",
            graphTitleFontColor : "#666",
            graphSubTitleFontFamily : "'Arial'",
            graphSubTitleFontSize : 18,
            graphSubTitleFontStyle : "normal",
            graphSubTitleFontColor : "#666",
            inGraphDataTmpl: "<%=(v1 == ''? '' : v1+' = ')+ roundToWithThousands(config,v2,2)%>",
            inGraphDataFontColor: "#666",
            legend : true,
            legendFontFamily : "'Arial'",
            legendFontSize : 9,
            legendFontStyle : "normal",
            legendFontColor : "#666",
            legendBlockSize : 50,
            legendBorders : true,
            legendBordersWidth : 1,
            legendBordersColors : "#666",
            annotateDisplay : false,
            spaceTop : 0,
            spaceBottom : 0,
            spaceLeft : 0,
            spaceRight : 0,
            logarithmic: true,
            animationSteps : 50,
            rotateLabels : "smart",
            xAxisSpaceOver : 0,
            xAxisSpaceUnder : 0,
            xAxisLabelSpaceAfter : 0,
            xAxisLabelSpaceBefore : 0,
            legendBordersSpaceBefore : 0,
            legendBordersSpaceAfter : 0,
            footNoteSpaceBefore : 0,
            footNoteSpaceAfter : 0,
            startAngle : 0,
            dynamicDisplay : false
        }

any help .. ?

**Comment by luisrudge** [comment] 2015-02-03 12:32
It's not working.

**Comment by FVANCOP** [comment] 2015-02-03 12:48
Sorry, but the information provided is insufficient... Can someone provide a code where the problem appears, the Operating System and the browser version where it occurs. Without a complete  information, I cannot help... On my PC with Firefox/IExplorer/Chrome, I have no problem.

**Comment by alexdd55** [comment] 2015-06-12 13:57
i played around with options now for hours and didn't get the legend.
the sample is showing it, so its not an browser issue.
all other options are working fine and do as shown in documentation.

**Comment by alexdd55** [comment] 2015-06-12 17:36
Problem solved on my side.
Instead of "label" it takes "title" for the legend, without the title it just doesn't render the legend.

**Comment by mgkimsal** [comment] 2015-06-12 20:25
@alexdd55 - can you add some specifics?  Instead of 'label' where?  

How are you rendering a legend?

@FVANCOP - sorry to bug you on this, but can you elaborate on " legend is more flexible : you can now draw it whereever you want" with pointing to the specific docs that illustrate this?  I'm not finding anything about how to render legends.  I've got one chart that just 'does' it, based on 'legend:true' and a template in the options, but it's not working for any other charts.

**Comment by alexdd55** [comment] 2015-06-12 20:50
@mgkimsal 
in a Pie chart the data looks like that:
```var mydata2 = [
	{
		value : 30,
		color: "#D97041",
    *title : "data1"*
	}
]``` 

but in chartjs the data looked like that
```var mydata2 = [
	{
		value : 30,
		color: "#D97041",
    *label : "data1"*
	}
]```

**Comment by mgkimsal** [comment] 2015-06-12 20:51
thank you - I've been working on this this afternoon, and your earlier post helped, but I've now run in to a separate logical issue concerning stacked bar graphs, and opened a separate issue #305 on that.  Thanks!

**Comment by FVANCOP** [comment] 2015-06-13 17:01
@alexdd55 : Thanks for discovering this differerence between ChartNew.js and Chart.js; In previous version of Chart.js, legend was an additional feature developped by someone and in this version, it was with "title"... I have just reproduced what was possible in first version of Chart.js. I will check if I can update the code of ChartNew.js to allow title and label :-)

Regards,
François

**Comment by FVANCOP** [comment] 2015-06-13 17:25
@mgkimsal : legend position - see https://github.com/FVANCOP/ChartNew.js/wiki/100_090_Legend#legendposx

**Comment by FVANCOP** [comment] 2015-06-13 21:41
ChartNew.js allows now also "label" ; but "title" is recommended...

I will close this issue; If other issues are encountered with legends, please open another issue.

Thanks @alexdd55  for his analyse !

**Closed by FVANCOP** 2015-06-13 21:41 UTC
Labels: bug
